#!/usr/bin/env bash
#
# install-worker.sh — provision a Scrappy worker on a fresh mini-PC.
#
# What it does (idempotent — re-run is safe):
#   1. Installs Docker + compose plugin if missing
#   2. Prompts for worker token, GHCR PAT, and (optional) MinIO creds
#   3. Writes /opt/scrappy/worker.env (mode 600)
#   4. Writes /opt/scrappy/docker-compose.yml (worker + watchtower)
#   5. docker login ghcr.io with the PAT
#   6. docker compose pull && up -d
#   7. Tails the worker log briefly to confirm boot
#
# After the first run, no manual updates are needed: Watchtower polls GHCR
# every 5 min and rolls the container automatically when a new image lands.
#
# Usage:
#   sudo ./install-worker.sh
#
# Or non-interactively (useful for re-runs / config management):
#   sudo WORKER_TOKEN=wk_live_... GHCR_USER=kevin GHCR_PAT=ghp_... \
#        S3_ENDPOINT=https://... S3_BUCKET_SCREENSHOTS=... \
#        S3_ACCESS_KEY_ID=... S3_SECRET_ACCESS_KEY=... \
#        ./install-worker.sh

set -euo pipefail

# ─── paths ───────────────────────────────────────────────────────────────
SCRAPPY_DIR=/opt/scrappy
WORKER_ENV="${SCRAPPY_DIR}/worker.env"
COMPOSE_FILE="${SCRAPPY_DIR}/docker-compose.yml"
WORKER_IMAGE=ghcr.io/xupegroup/scrappy-worker:latest

# ─── pre-flight ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "This script must run as root (sudo $0)." >&2
  exit 1
fi

step()  { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }
fail()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

prompt_required() {
  local var=$1 desc=$2
  if [[ -z "${!var:-}" ]]; then
    read -rp "  ${desc}: " val
    [[ -n "$val" ]] || fail "${desc} is required"
    printf -v "$var" '%s' "$val"
  fi
}

prompt_secret() {
  local var=$1 desc=$2
  if [[ -z "${!var:-}" ]]; then
    read -srp "  ${desc} (input hidden): " val
    echo
    [[ -n "$val" ]] || fail "${desc} is required"
    printf -v "$var" '%s' "$val"
  fi
}

prompt_optional() {
  local var=$1 desc=$2 default=${3:-}
  if [[ -z "${!var:-}" ]]; then
    if [[ -n "$default" ]]; then
      read -rp "  ${desc} [${default}]: " val
      val=${val:-$default}
    else
      read -rp "  ${desc} (optional, blank to skip): " val
    fi
    printf -v "$var" '%s' "$val"
  fi
}

# ─── 1. Docker ───────────────────────────────────────────────────────────
step "Checking Docker"
if ! command -v docker >/dev/null 2>&1; then
  step "Installing Docker"
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"
else
  ok "Docker already present ($(docker --version))"
fi

if ! docker compose version >/dev/null 2>&1; then
  fail "docker compose plugin missing — run 'apt-get install docker-compose-plugin' or upgrade Docker."
fi

# ─── 2. Prompts ──────────────────────────────────────────────────────────
step "Worker configuration"
prompt_optional WORKER_NAME       "Worker name (shown in admin UI)" "$(hostname)"
prompt_optional API_BASE_URL      "Control plane API URL"           "https://api.scrappy.hu"
prompt_optional WORKER_CONCURRENCY "Concurrent jobs per worker"     "2"
prompt_secret   WORKER_TOKEN      "Worker token (wk_live_...)"

step "GHCR credentials (private worker image registry)"
prompt_required GHCR_USER         "GitHub user for the read-only PAT"
prompt_secret   GHCR_PAT          "GitHub PAT with read:packages scope"

step "Screenshot storage (MinIO/S3) — leave blank to disable"
prompt_optional S3_ENDPOINT       "S3 endpoint URL"
S3_REGION=${S3_REGION:-us-east-1}
S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
if [[ -n "$S3_ENDPOINT" ]]; then
  prompt_required S3_BUCKET_SCREENSHOTS "Bucket name"
  prompt_required S3_ACCESS_KEY_ID      "Access key ID"
  prompt_secret   S3_SECRET_ACCESS_KEY  "Secret access key"
fi

# ─── 3. /opt/scrappy ─────────────────────────────────────────────────────
step "Provisioning ${SCRAPPY_DIR}"
mkdir -p "$SCRAPPY_DIR"
chmod 700 "$SCRAPPY_DIR"

# ─── 4. worker.env ───────────────────────────────────────────────────────
step "Writing ${WORKER_ENV}"
umask 077
cat > "$WORKER_ENV" <<EOF
# Generated by install-worker.sh on $(date --iso-8601=seconds)
# Do not commit this file anywhere.

WORKER_NAME=${WORKER_NAME}
WORKER_TOKEN=${WORKER_TOKEN}
API_BASE_URL=${API_BASE_URL}
WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
NODE_ENV=production
LOG_LEVEL=info

S3_ENDPOINT=${S3_ENDPOINT}
S3_REGION=${S3_REGION}
S3_BUCKET_SCREENSHOTS=${S3_BUCKET_SCREENSHOTS:-}
S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-}
S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-}
S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
EOF
chmod 600 "$WORKER_ENV"
ok "Wrote ${WORKER_ENV} (mode 600)"

# ─── 5. docker-compose.yml ───────────────────────────────────────────────
step "Writing ${COMPOSE_FILE}"
cat > "$COMPOSE_FILE" <<EOF
# Generated by install-worker.sh — re-run the script to regenerate.

name: scrappy-worker

services:
  worker:
    image: ${WORKER_IMAGE}
    container_name: scrappy-worker
    restart: unless-stopped
    env_file: ${WORKER_ENV}
    mem_limit: 2g
    labels:
      # Watchtower picks up only labeled containers.
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: scrappy-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the host's docker config so Watchtower can pull from private GHCR.
      - /root/.docker/config.json:/config.json:ro
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      # Poll every 5 minutes. New :latest digest from CI rolls out within
      # one cycle. Tune up if you want faster propagation.
      WATCHTOWER_POLL_INTERVAL: "300"
      # Give the worker time to drain in-flight jobs (the worker itself
      # honors SIGTERM with a 30s drain budget).
      WATCHTOWER_TIMEOUT: "45s"
      # Remove the old image after a successful update so disk doesn't grow.
      WATCHTOWER_CLEANUP: "true"
EOF
ok "Wrote ${COMPOSE_FILE}"

# ─── 6. GHCR login ───────────────────────────────────────────────────────
step "Authenticating to ghcr.io"
echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
ok "docker login ghcr.io OK"

# ─── 7. Pull + start ─────────────────────────────────────────────────────
step "Pulling worker image"
docker compose -f "$COMPOSE_FILE" pull
step "Starting worker + watchtower"
docker compose -f "$COMPOSE_FILE" up -d
ok "docker compose up -d done"

# ─── 8. Verify ───────────────────────────────────────────────────────────
step "Waiting 6s for boot, then tailing worker log"
sleep 6
docker logs scrappy-worker --tail 30 || true

cat <<'EOM'

──────────────────────────────────────────────────────────────────────
✓ Worker installed and running.

Useful commands:
  docker logs -f scrappy-worker        # live worker log
  docker logs -f scrappy-watchtower    # update daemon log
  docker compose -f /opt/scrappy/docker-compose.yml ps

To rotate the worker token: edit /opt/scrappy/worker.env, then
  docker compose -f /opt/scrappy/docker-compose.yml restart worker

To uninstall completely:
  docker compose -f /opt/scrappy/docker-compose.yml down
  rm -rf /opt/scrappy
  docker logout ghcr.io
──────────────────────────────────────────────────────────────────────
EOM
