#!/usr/bin/env bash
#
# install-worker.sh — provision a Scrappy worker on a fresh mini-PC.
#
# What it does (idempotent — re-run is safe):
#   1. Installs Docker + compose plugin if missing
#   2. Prompts for a Scrappy worker token (the only secret you type)
#   3. Calls api.scrappy.hu/v1/internal/bootstrap with that token to fetch
#      GHCR pull credentials — workers never need direct S3 / registry creds
#   4. Writes /opt/scrappy/worker.env (mode 600)
#   5. Writes /opt/scrappy/docker-compose.yml (worker + watchtower)
#   6. docker login ghcr.io with the bootstrap-issued PAT
#   7. docker compose pull && up -d
#   8. Tails the worker log briefly to confirm boot
#
# After the first run, no manual updates are needed: Watchtower polls GHCR
# every 5 min and rolls the container automatically when a new image lands.
#
# Usage:
#   sudo ./install-worker.sh
#
# Only one prompt: the worker token. Everything else is hardcoded — workers
# in the wild always point at api.scrappy.hu, and the worker's display name
# comes from the admin UI (the API returns the canonical name on identity
# confirm, so the local label is irrelevant).
#
# Override defaults via env if you really need to (e.g. dev/staging API):
#   sudo WORKER_TOKEN=wk_live_... API_BASE_URL=https://api.staging.scrappy.hu \
#        WORKER_CONCURRENCY=4 ./install-worker.sh

set -euo pipefail

# ─── paths + defaults ────────────────────────────────────────────────────
SCRAPPY_DIR=/opt/scrappy
WORKER_ENV="${SCRAPPY_DIR}/worker.env"
COMPOSE_FILE="${SCRAPPY_DIR}/docker-compose.yml"
WORKER_IMAGE=ghcr.io/xupegroup/scrappy-worker:latest

# Hardcoded defaults — env-var override stays available for dev/staging.
API_BASE_URL=${API_BASE_URL:-https://api.scrappy.hu}
WORKER_CONCURRENCY=${WORKER_CONCURRENCY:-2}
# Local display name only — the API returns the canonical name on identity
# confirm, so this just shows up in the first ~1s of logs before the
# overwrite. Hostname is a sane "where am I" hint for debugging.
WORKER_NAME=${WORKER_NAME:-$(hostname)}

# ─── pre-flight ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "This script must run as root (sudo $0)." >&2
  exit 1
fi

step()  { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }
fail()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

prompt_secret() {
  local var=$1 desc=$2
  if [[ -z "${!var:-}" ]]; then
    read -srp "  ${desc} (input hidden): " val
    echo
    [[ -n "$val" ]] || fail "${desc} is required"
    printf -v "$var" '%s' "$val"
  fi
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command missing: $1"
}

# ─── 1. Docker + curl + jq ───────────────────────────────────────────────
step "Checking host prerequisites"
if ! command -v docker >/dev/null 2>&1; then
  step "Installing Docker"
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"
else
  ok "Docker already present ($(docker --version))"
fi
if ! docker compose version >/dev/null 2>&1; then
  fail "docker compose plugin missing — run 'apt-get install docker-compose-plugin' or upgrade Docker."
fi
require_cmd curl
if ! command -v jq >/dev/null 2>&1; then
  step "Installing jq"
  apt-get update -qq && apt-get install -y -qq jq
fi

# ─── 2. Prompt ───────────────────────────────────────────────────────────
step "Worker configuration"
echo "  api: ${API_BASE_URL}"
echo "  name: ${WORKER_NAME}    concurrency: ${WORKER_CONCURRENCY}"
prompt_secret WORKER_TOKEN "Worker token (wk_live_...)"

# ─── 3. Bootstrap call ───────────────────────────────────────────────────
step "Fetching registry credentials from ${API_BASE_URL}"
BOOTSTRAP_URL="${API_BASE_URL%/}/v1/internal/bootstrap"
BOOTSTRAP_RESPONSE=$(curl -fsS -X POST \
  -H "X-Worker-Token: ${WORKER_TOKEN}" \
  -H "content-type: application/json" \
  "$BOOTSTRAP_URL" \
  || fail "Bootstrap call failed — is the worker token valid? Is ${BOOTSTRAP_URL} reachable?")

GHCR_USER=$(printf '%s' "$BOOTSTRAP_RESPONSE" | jq -r '.ghcr_user // empty')
GHCR_PAT=$(printf '%s' "$BOOTSTRAP_RESPONSE" | jq -r '.ghcr_pat // empty')
if [[ -z "$GHCR_USER" || -z "$GHCR_PAT" ]]; then
  fail "Bootstrap response missing ghcr_user / ghcr_pat — check API GHCR_USERNAME and GHCR_PAT envs."
fi
ok "Bootstrap creds received (user: ${GHCR_USER})"

# ─── 4. /opt/scrappy ─────────────────────────────────────────────────────
step "Provisioning ${SCRAPPY_DIR}"
mkdir -p "$SCRAPPY_DIR"
chmod 700 "$SCRAPPY_DIR"

# ─── 5. worker.env ───────────────────────────────────────────────────────
step "Writing ${WORKER_ENV}"
umask 077
cat > "$WORKER_ENV" <<EOF
# Generated by install-worker.sh on $(date --iso-8601=seconds)
# Do not commit this file anywhere.

WORKER_NAME=${WORKER_NAME}
WORKER_TOKEN=${WORKER_TOKEN}
API_BASE_URL=${API_BASE_URL}
WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
NODE_ENV=production
LOG_LEVEL=info
EOF
chmod 600 "$WORKER_ENV"
ok "Wrote ${WORKER_ENV} (mode 600)"

# ─── 6. docker-compose.yml ───────────────────────────────────────────────
step "Writing ${COMPOSE_FILE}"
cat > "$COMPOSE_FILE" <<EOF
# Generated by install-worker.sh — re-run the script to regenerate.

name: scrappy-worker

services:
  worker:
    image: ${WORKER_IMAGE}
    container_name: scrappy-worker
    restart: unless-stopped
    env_file: ${WORKER_ENV}
    mem_limit: 2g
    labels:
      # Watchtower picks up only labeled containers.
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: scrappy-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the host's docker config so Watchtower can pull from private GHCR.
      - /root/.docker/config.json:/config.json:ro
    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      # Poll every 5 minutes. New :latest digest from CI rolls out within
      # one cycle. Tune up if you want faster propagation.
      WATCHTOWER_POLL_INTERVAL: "300"
      # Give the worker time to drain in-flight jobs (the worker itself
      # honors SIGTERM with a 30s drain budget).
      WATCHTOWER_TIMEOUT: "45s"
      # Remove the old image after a successful update so disk doesn't grow.
      WATCHTOWER_CLEANUP: "true"
EOF
ok "Wrote ${COMPOSE_FILE}"

# ─── 7. GHCR login ───────────────────────────────────────────────────────
step "Authenticating to ghcr.io"
echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin >/dev/null
ok "docker login ghcr.io OK"

# ─── 8. Pull + start ─────────────────────────────────────────────────────
step "Pulling worker image"
docker compose -f "$COMPOSE_FILE" pull
step "Starting worker + watchtower"
docker compose -f "$COMPOSE_FILE" up -d
ok "docker compose up -d done"

# ─── 9. Verify ───────────────────────────────────────────────────────────
step "Waiting 6s for boot, then tailing worker log"
sleep 6
docker logs scrappy-worker --tail 30 || true

cat <<'EOM'

──────────────────────────────────────────────────────────────────────
✓ Worker installed and running.

Useful commands:
  docker logs -f scrappy-worker        # live worker log
  docker logs -f scrappy-watchtower    # update daemon log
  docker compose -f /opt/scrappy/docker-compose.yml ps

To rotate the worker token: edit /opt/scrappy/worker.env, then
  docker compose -f /opt/scrappy/docker-compose.yml restart worker

To rotate the GHCR PAT (after the operator updates it on the control plane):
  sudo /path/to/install-worker.sh   # re-run, picks up the new bootstrap creds

To uninstall completely:
  docker compose -f /opt/scrappy/docker-compose.yml down
  rm -rf /opt/scrappy
  docker logout ghcr.io
──────────────────────────────────────────────────────────────────────
EOM
